update `Cargo.toml`edition to 2024 (#20)
* About “hal” changed to “cha32_hal” for newcomers to understand

* About “hal” changed to “cha32_hal” for newcomers to understand

* Correction "use hal" ->"ch32_hal" ,and  "hal-> ch32_hal" of the main function

* add the details about readme

* update details about readme

* Update README.md

* add details about readme

* fix  rust-analyzer test erro

error[E0463]: can't find crate for test

* Update Cargo.toml

update edition 2021 -> 2024